version: "2.4"
services:
  docspell:
    image: olaxe/docspell:latest
    restart: unless-stopped
    environment:
      # To be changed below
      TZ: 'Europe/Paris'
      DOCSPELL_DB_TYPE: 'mariadb'
      DOCSPELL_DB_HOST: 'core-mariadb'
      DOCSPELL_DB_PORT: '3306'
      DOCSPELL_DB_NAME: 'docspell'
      DOCSPELL_DB_USER: 'docspell'
      DOCSPELL_DB_PASS: 'some-secret'
      DOCSPELL_RS_BASE_URL: 'https://dms.my-domain.com'
      # Can be kept as default below
      DEBUG: "false"
      DOCSPELL_RS_APP_NAME: "Docspell"
      DOCSPELL_RS_APP_ID: "rest1"
      DOCSPELL_RS_BIND_ADDRESS: "0.0.0.0"
      DOCSPELL_RS_BIND_PORT: "7880"
      DOCSPELL_RS_MAX_ITEM_PAGE_SIZE: "200"
      DOCSPELL_RS_MAX_NOTE_LENGTH: "180"
      DOCSPELL_RS_SHOW_CLASSIFICATION_SETTINGS: "true"
      DOCSPﾃ記L_RS_AUTH_SERVER_SECRET: "hex:caffee"
      DOCSPﾃ記L_RS_AUTH_SESSION_VALID: "5 minutes"
      DOCSPﾃ記L_RS_REMEMBER_ME_ENABLED: "true"
      DOCSPﾃ記L_RS_REMEMBER_ME_VALID: "30 days"
      DOCSPELL_RS_INTEGRATION_ENDPOINT_ENABLED: "false"
      DOCSPELL_RS_INTEGRATION_ENDPOINT_PRIORITY: "low"
      DOCSPELL_RS_INTEGRATION_ENDPOINT_SOURCE_NAME: "integration"
      DOCSPELL_RS_INTEGRATION_ENDPOINT_ALLOWED_IPS_ENABLED: "false"
      DOCSPELL_RS_INTEGRATION_ENDPOINT_ALLOWED_IPS_IPS: "127.0.0.1"
      DOCSPELL_RS_INTEGRATION_ENDPOINT_HTTP_BASIC_ENABLED: "false"
      DOCSPELL_RS_INTEGRATION_ENDPOINT_HTTP_BASIC_REALM: "Docspell Integration"
      DOCSPELL_RS_INTEGRATION_ENDPOINT_HTTP_BASIC_USER: "docspell-int"
      DOCSPELL_RS_INTEGRATION_ENDPOINT_HTTP_BASIC_PASSWORD: "docspell-int"
      DOCSPELL_RS_INTEGRATION_ENDPOINT_HTTP_HEADER_ENABLED: "false"
      DOCSPELL_RS_INTEGRATION_ENDPOINT_HTTP_HEADER_NAME: "Docspell-Integration"
      DOCSPELL_RS_INTEGRATION_ENDPOINT_HTTP_HEADER_VALUE: "some-secret"
      DOCSPELL_RS_ADMIN_ENDPOINT_SECRET: ""
      DOCSPELL_RS_FULL_TEXT_SEARCH_ENABLED: "true"
      DOCSPELL_RS_FULL_TEXT_SEARCH_SOLR_URL: "http://localhost:8983/solr/docspell"
      DOCSPELL_RS_FULL_TEXT_SEARCH_SOLR_COMMIT_WITHIN: "1000"
      DOCSPELL_RS_FULL_TEXT_SEARCH_SOLR_LOG_VERBOSE: "false"
      DOCSPELL_RS_FULL_TEXT_SEARCH_SOLR_DEF_TYPE: "lucene"
      DOCSPELL_RS_FULL_TEXT_SEARCH_SOLR_Q_OP: "OR"
      DOCSPELL_RS_BACKEND_MAIL_DEBUG: "false"
      DOCSPELL_RS_BACKEND_SIGNUP_MODE: "open"
      DOCSPELL_RS_BACKEND_SIGNUP_NEW_INVITE_PASSWORD: ""
      DOCSPELL_RS_BACKEND_SIGNUP_INVITE_TIME: "3 days"
      DOCSPELL_RS_BACKEND_FILES_CHUNK_SIZE: "524288"
      # https://docspell.org/docs/configure/#memory-usage    
      JAVA_OPTS: "-Xmx1536M"
    ports:
      - "7880:7880"
    network_mode: "hassio"
    volumes:
      - /mnt/data/supervisor/share/docspell_solr-data:/var/solr/data
